# Generated by Django 5.2.2 on 2025-06-17 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioElegibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
                ('sueño_horas', models.PositiveIntegerField()),
                ('comida_reciente', models.PositiveIntegerField()),
                ('meses_ultima_donacion', models.PositiveIntegerField()),
                ('tiene_documento', models.BooleanField()),
                ('genero', models.CharField(max_length=10)),
                ('criterios_consultar', models.JSONField()),
                ('criterios_exclusion', models.JSONField()),
                ('resultado', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
