# Generated by Django 5.2.2 on 2025-10-16 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0002_achievement_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Identificador único para el ítem.', max_length=100, unique=True)),
                ('value', models.IntegerField(default=0, help_text='Valor del ítem, si aplica.')),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='item_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_slug', models.CharField(max_length=64)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('last_awarded', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item_slug')},
            },
        ),
    ]
