# Generated by Django 5.2.2 on 2025-10-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0003_items_useritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='canjeable',
            field=models.BooleanField(default=True, help_text='Indica si el ítem puede ser canjeado.'),
        ),
    ]
