# Generated by Django 5.2.2 on 2025-09-04 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_cancellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.donationcenter'),
        ),
    ]
