"""
Django settings for donapp project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-74yxv%@tacrel)!%&xx$fwh#xv1oc+%1$_8se479!8xi)0j+7l'

# SECURITY WARNING: don't run with debug turned on in production!


#INICIO DE CAMBIO1
"""
DEBUG = False  # cambiar a true si no funciona el backend
CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGINS = [
   "https://midonapp.cl",
   "https://www.midonapp.cl",  # custom scheme for mobile app if needed
]
# Esto es para la pagina web
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

ALLOWED_HOSTS = ['midonapp.cl', 'www.midonapp.cl', '10.0.2.2','127.0.0.1', 'localhost','*']
"""
#FINAL DE CAMBIO1
# ESTO ES LO QUE SE pone en CAMBIO1 SI QUIEREN PROBAR EL BACKEND EN LOCAL:

DEBUG = True

CORS_ORIGIN_ALLOW_ALL = True
ALLOWED_HOSTS = ['10.0.2.2','localhost', '*']



from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # si vas a usar DRF
    'rest_framework.authtoken',
    'trivia',
    'usuarios',
    'elegibilidad',
    'campanias',
    'appointments',
    'django_extensions',
    'survey',
    'chats',
    'Whatsapp',
    'logros',
    'corsheaders',
    'desafios',
    'historias',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'donapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'donapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'donapp_db',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',  # o la IP si es externa
        'PORT': '5432',
    }
}
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-chatbot-cache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

TIME_ZONE = "America/Santiago"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ALGORITHM': 'HS256',  # Usa SHA-256 por defecto
    'SIGNING_KEY': SECRET_KEY,
}

LOGGING = {
    'version': 1,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {'django.db.backends': {'handlers': ['console'], 'level': 'WARNING'}},
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jose.manzano@sansano.usm.cl'
EMAIL_HOST_PASSWORD = 'sfum bjax gahr wsbb'  # No uses tu contraseña real
DEFAULT_FROM_EMAIL = "Donapp <jose.manzano@sansano.usm.cl>"

ONESIGNAL_APP_ID = "608bb723-bb79-4000-a2d0-2498b0818337"
ONESIGNAL_API_KEY = "os_v2_app_mcf3oi53pfaabiwqesmlbamdg4n5qkplobqeulukecqagfowfcvpjwvaccgl7ro2coepzshkq5omtf3revcy4czxu4rdzuwgmvi3f7q"

# settings.py
# 🔹 API de RunPod
RUNPOD_API_KEY = os.getenv("RUNPOD_API_KEY", "")
RUNPOD_ENDPOINT = os.getenv("RUNPOD_ENDPOINT", "")
RUNPOD_ENDPOINT_ID = os.getenv("RUNPOD_ENDPOINT_ID", "")


# 🔹 Qdrant (si usas búsqueda semántica)
QDRANT_HOST = "localhost"
QDRANT_PORT = 6333  # o 6334 si cambiaste el mapeo
QDRANT_API_KEY = "" # vacío si no seteaste en compose
QDRANT_COLLECTION_A = os.getenv("COLL_A", "kb_a")
QDRANT_COLLECTION_B = os.getenv("COLL_B", "kb_b")

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Santiago" 

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "enviar-recordatorios-donacion": {
        "task": "campanias.tasks.enviar_recordatorios_donacion",
        "schedule": crontab(hour=9, minute=38),  # todos los días a las 09:00
    },
    "recordatorio-citas-manana": {
        "task": "campanias.tasks.enviar_recordatorio_citas_manana",  # <- apuntar a campanias
        "schedule": crontab(hour=23, minute=38),
    },
}



