# Generated by Django 5.2.2 on 2025-09-04 09:00
from django.db import migrations
from datetime import date, timedelta
import random

def crear_usuarios_prueba(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('usuarios', 'UserProfile')

    # ===== Crear admin de prueba =====
    if not User.objects.filter(username='donante_prueba').exists():
        user = User.objects.create_superuser(
            username='donante_prueba',
            email='donante@ejemplo.com',
            password='password123'
        )
        UserProfile.objects.create(
            user=user,
            sexo='M',
            apto_para_donar=True,
            fecha_ultima_donacion=date.today() - timedelta(days=60),
            tipo_sangre='O+',
            region='Metropolitana',
            provincia='Santiago',
            comuna='Santiago Centro',
            xp=150,
            nivel=3,
            is_admin=True,
            telefono='912345678',
            preferencias_notificacion=['push', 'correo']
        )

    # ===== Crear 200 usuarios aleatorios =====
    regiones = {
        'Metropolitana de Santiago': {
            'Santiago': ['Santiago Centro', 'Providencia', 'Ñuñoa'],
            'Maipo': ['San Bernardo', 'Buin', 'Calera de Tango']
        },
        'Valparaíso': {
            'Valparaíso': ['Viña del Mar', 'Valparaíso', 'Quilpué'],
            'San Antonio': ['San Antonio', 'Cartagena', 'El Tabo']
        },
        'Biobío': {
            'Concepción': ['Concepción', 'Talcahuano', 'Hualpén'],
            'Bío Bío': ['Los Ángeles', 'Chiguayante', 'Tome']
        }
    }
    sexos = ['M', 'F', 'O']
    tipos_sangre = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']
    for i in range(1, 201):
        username = f'usuario{i}'
        if User.objects.filter(username=username).exists():
            continue
        user = User.objects.create_user(
            username=username,
            email=f'{username}@ejemplo.com',
            password='password123',
            first_name=f'Nombre{i}',
            last_name=f'Apellido{i}'
        )
        region = random.choice(list(regiones.keys()))
        provincia = random.choice(list(regiones[region].keys()))
        comuna = random.choice(regiones[region][provincia])
        UserProfile.objects.create(
            user=user,
            sexo=random.choice(sexos),
            apto_para_donar=random.choice([True, False]),
            fecha_ultima_donacion=date.today() - timedelta(days=random.randint(0, 180)),
            tipo_sangre=random.choice(tipos_sangre),
            region=region,
            provincia=provincia,
            comuna=comuna,
            xp=random.randint(0, 500),
            nivel=random.randint(1, 10),
            is_admin=False,
            telefono=f'9{random.randint(10000000, 99999999)}',
            preferencias_notificacion=random.sample(['push', 'whatsapp', 'correo'], k=random.randint(1,3))
        )

def borrar_usuarios_prueba(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username__startswith='usuario').delete()
    User.objects.filter(username='donante_prueba').delete()

class Migration(migrations.Migration):
    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_usuarios_prueba, borrar_usuarios_prueba),
    ]
