# Generated by Django 5.2.2 on 2025-09-04 10:02

# Generated by Django 5.2.2 on 2025-10-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userprofile_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
