# Generated by Django 5.2.2 on 2025-10-15 19:13
# Generated by Django 5.2.2 on 2025-10-15 21:14

# Generated by Django 5.2.2 on 2025-10-15 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_userprofile_amigos_friendrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_color', models.IntegerField(default=4294234549)),
                ('shirt_color', models.IntegerField(default=4283277797)),
                ('accessory', models.CharField(default='none', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
