# Generated by Django 5.2.2 on 2025-10-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafiosemanal',
            name='tipo',
            field=models.CharField(choices=[('donacion', 'Donación'), ('asistencia', 'Asistencia a campaña'), ('abrir_app', 'Apertura de la app'), ('trivia', 'Responder Trivia'), ('compartir', 'Compartir en Redes'), ('jugar', 'Jugar Minijuego'), ('ver_campana', 'Ver una Campaña')], max_length=50),
        ),
    ]
