// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_WEB',
    appId: 'YOUR_APP_ID_WEB',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'donapp-project-id',
    authDomain: 'donapp-project-id.firebaseapp.com',
    storageBucket: 'donapp-project-id.firebasestorage.app',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_ANDROID',
    appId: 'YOUR_APP_ID_ANDROID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'donapp-project-id',
    storageBucket: 'donapp-project-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_IOS',
    appId: 'YOUR_APP_ID_IOS',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'donapp-project-id',
    storageBucket: 'donapp-project-id.firebasestorage.app',
    iosBundleId: 'com.example.your-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_MACOS',
    appId: 'YOUR_APP_ID_MACOS',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'donapp-project-id',
    storageBucket: 'donapp-project-id.firebasestorage.app',
    iosBundleId: 'com.example.your-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_WINDOWS',
    appId: 'YOUR_APP_ID_WINDOWS',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'donapp-project-id',
    authDomain: 'donapp-project-id.firebaseapp.com',
    storageBucket: 'donapp-project-id.firebasestorage.app',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );
}
