// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQSLSsYLzkk79Peb4iM_b6I-GLRuL7kyc',
    appId: '1:684595741464:web:7f27ff3bb40290019a546d',
    messagingSenderId: '684595741464',
    projectId: 'donapp-3c6a3',
    authDomain: 'donapp-3c6a3.firebaseapp.com',
    storageBucket: 'donapp-3c6a3.firebasestorage.app',
    measurementId: 'G-SXHZXL9S1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_AoWrYEEPqUtRbzmxDuKHHwO6KO8EEhg',
    appId: '1:684595741464:android:0bf9e13bec51488a9a546d',
    messagingSenderId: '684595741464',
    projectId: 'donapp-3c6a3',
    storageBucket: 'donapp-3c6a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGB1Ve7tD3a0qGzV5sKR-nmAc0sHsO6lM',
    appId: '1:684595741464:ios:7b38e01a594183ce9a546d',
    messagingSenderId: '684595741464',
    projectId: 'donapp-3c6a3',
    storageBucket: 'donapp-3c6a3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGB1Ve7tD3a0qGzV5sKR-nmAc0sHsO6lM',
    appId: '1:684595741464:ios:7b38e01a594183ce9a546d',
    messagingSenderId: '684595741464',
    projectId: 'donapp-3c6a3',
    storageBucket: 'donapp-3c6a3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQSLSsYLzkk79Peb4iM_b6I-GLRuL7kyc',
    appId: '1:684595741464:web:759d91e6bb5d51c99a546d',
    messagingSenderId: '684595741464',
    projectId: 'donapp-3c6a3',
    authDomain: 'donapp-3c6a3.firebaseapp.com',
    storageBucket: 'donapp-3c6a3.firebasestorage.app',
    measurementId: 'G-146PRGTT7F',
  );
}
