# Generated by Django 5.2.2 on 2025-08-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('comuna', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('horario', models.CharField(max_length=100)),
                ('grupo_sanguineo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3)),
                ('rh', models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='campañas/')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('borrador', 'Borrador'), ('cancelada', 'Cancelada')], default='borrador', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
