# Generated by Django 5.2.2 on 2025-08-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='campanias/'),
        ),
    ]
