# Generated by Django 5.2.2 on 2025-09-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0002_alter_campaña_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaña',
            new_name='Campania',
        ),
    ]
