# Generated by Django 5.2.2 on 2025-09-03 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0003_rename_campaña_campania'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_email', models.BooleanField(default=False)),
                ('enviado_push', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reaccion', models.CharField(blank=True, max_length=20, null=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanias.campania')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
