# Generated by Django 5.2.2 on 2025-09-04 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0004_enviocampania'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviocampania',
            options={'verbose_name_plural': 'Envíos de Campaña'},
        ),
        migrations.RenameField(
            model_name='enviocampania',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='nombre',
        ),
        migrations.AlterUniqueTogether(
            name='enviocampania',
            unique_together={('campania', 'destinatario')},
        ),
        migrations.AddField(
            model_name='campania',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campania',
            name='mensaje',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campania',
            name='titulo',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campania',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enviocampania',
            name='abierto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enviocampania',
            name='clics',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campania',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('programada', 'Programada'), ('en_cola', 'En Cola')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='campania',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='enviocampania',
            name='campania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='campanias.campania'),
        ),
        migrations.AlterField(
            model_name='enviocampania',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_campanias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReaccionCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(choices=[('feliz', 'Cara Feliz'), ('sonriente', 'Cara Sonriente'), ('neutro', 'Cara Neutra'), ('fruncido', 'Cara Fruncida'), ('enojado', 'Cara Enojada')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reaccion', to='campanias.enviocampania')),
            ],
            options={
                'verbose_name_plural': 'Reacciones de Campaña',
            },
        ),
        migrations.RemoveField(
            model_name='enviocampania',
            name='reaccion',
        ),
        migrations.CreateModel(
            name='OptOutCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='campanias.campania')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanias_opt_out', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exclusiones de Campaña',
                'unique_together': {('campania', 'usuario')},
            },
        ),
    ]
