# Generated by Django 5.2.2 on 2025-09-04 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0005_alter_enviocampania_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaccioncampania',
            name='envio',
        ),
        migrations.AlterModelOptions(
            name='enviocampania',
            options={},
        ),
        migrations.RenameField(
            model_name='enviocampania',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='enviocampania',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='campania',
            name='fecha_programada',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='campania',
            name='nombre',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enviocampania',
            name='reaccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('borrador', 'Borrador'), ('cancelada', 'Cancelada')], default='borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='campania',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enviocampania',
            name='campania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanias.campania'),
        ),
        migrations.AlterField(
            model_name='enviocampania',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OptOutCampania',
        ),
        migrations.DeleteModel(
            name='ReaccionCampania',
        ),
        migrations.RemoveField(
            model_name='enviocampania',
            name='abierto',
        ),
        migrations.RemoveField(
            model_name='enviocampania',
            name='clics',
        ),
    ]
