# Generated by Django 5.2.2 on 2025-09-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0006_remove_reaccioncampania_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='programado_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviocampania',
            name='recibido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('borrador', 'Borrador'), ('cancelada', 'Cancelada'), ('programada', 'Programada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='enviocampania',
            name='reaccion',
            field=models.CharField(blank=True, choices=[('feliz', '😀'), ('sonriente', '🙂'), ('neutro', '😐'), ('fruncido', '🙁'), ('enojado', '😡'), ('agendar', 'Agendar'), ('opt_out', 'No por ahora'), ('error_envio', 'Error de envío')], max_length=20, null=True),
        ),
    ]
