# Generated by Django 5.2.2 on 2025-11-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.conversation'),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='route',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_canonical', models.CharField(max_length=300, unique=True)),
                ('answer_html', models.TextField()),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('action', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='chats.faqcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FAQRegex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=300, unique=True)),
                ('flags', models.CharField(blank=True, default='i', max_length=50)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='chats.faq')),
            ],
        ),
        migrations.CreateModel(
            name='FAQSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=300)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='chats.faq')),
            ],
            options={
                'unique_together': {('faq', 'text')},
            },
        ),
    ]
