# Generated by Django 5.2.2 on 2025-11-06 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_faqcategory_chatfeedback_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqregex',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regexes', to='chats.faq'),
        ),
        migrations.AlterField(
            model_name='faqregex',
            name='flags',
            field=models.CharField(default='i', max_length=16),
        ),
        migrations.AlterField(
            model_name='faqregex',
            name='pattern',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='faqregex',
            constraint=models.UniqueConstraint(fields=('faq', 'pattern'), name='uniq_faq_pattern'),
        ),
    ]
